mainapp/urls.py
from django.urls import path, re_path, include

import mainapp.views as mainapp


app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.products, name='index'),  # show products

    # show products for category_id=4
    # products/4
    path('<int:pk>', mainapp.products, name='category'),

    # show details of product with id=3
    # products/product/3
    path('product/<int:pk>/', mainapp.product, name='product'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя',
                            max_length=55,
                            unique=True)
    description = models.TextField(verbose_name='описание',
                                   blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    class Meta:
        ordering = ['name',]
        verbose_name = 'категорию'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory,
                                 on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта',
                            max_length=128)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта',
                                  max_length=60,
                                  blank=True)
    description = models.TextField(verbose_name='описание продукта',
                                   blank=True)
    price = models.DecimalField(verbose_name='цена продукта',
                                max_digits=8,
                                decimal_places=2,
                                default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе',
                                           default=0)

    class Meta:
        ordering = ['category']
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return '{} {}'.format(self.name, self.category.name)

mainapp/forms.py
from django import forms

# form to create ProductCategory
# this form is in adminapp.forms file

mainapp/views.py
from django.shortcuts import render
from django.urls import resolve
from django.http import HttpResponse, HttpResponseRedirect
from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404
from basket.models import Basket
import datetime
import random

now = datetime.datetime.now()
current_year = now.year


def get_hot_product():
    products = Product.objects.all()

    products_list = list(products)
    if products_list:
        _hot_product = random.choice(products_list) # i think its more elegant
    else:
        _hot_product = ['You forgot to fill db!']

    return _hot_product


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).\
        exclude(pk=hot_product.pk)[:3]
    return same_products


def products(request, pk=None):
    title = 'продукты'
    links_menu = ProductCategory.objects.order_by('name')
    # basket = get_basket(request.user)

    # if request.user.is_authenticated:
    #     basket = Basket.objects.filter(user=request.user)

    if pk != None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        ctx = {'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products,}

        return render(request, 'mainapp/products_list.html', ctx)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    # same_products = Product.objects.all()[3:5]

    ctx = {'title': title,
            'links_menu': links_menu,
            'hot_product': hot_product,
            'same_products': same_products,
            # 'basket': basket,
           }

    return render(request, 'mainapp/products_list.html', ctx)


def product(request, pk):
    title = 'детали'

    ctx = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
    }
    return render(request, 'mainapp/product.html', ctx)


def seed_db(request): # это код больше не нужен, делаю через management
    ProductCategory.objects.all().delete()
    Product.objects.all().delete()

    cat1 = ProductCategory()
    cat1.name = 'категория1'
    cat1.description = 'описания категории 1 бла бла бла 12314123'
    cat1.save()

    prod1 = Product()
    prod1.name = 'product1 имя'
    prod1.category = cat1
    prod1.save()

    print('[+] Created {}, {}'.format(cat1.name, prod1.name))

    cat2 = ProductCategory()
    cat2.name = 'категория22222'
    cat2.description = 'описаия егории 2 22222222222 бла 12314123'
    cat2.save()

    prod2 = Product()
    prod2.name = 'prod222222222'
    prod2.category = cat2
    prod2.save()

    print('[+] Created {}, {}'.format(cat2.name, prod2.name))
    return HttpResponse('<h1> Done! </h1> ')


# разобраться что это за хвост и либо убрать либо написать причину
# def categories(request, pk=None):
#     if pk is None:
#         return HttpResponseRedirect('/')
#     else:
#         links_menu = ProductCategory.objects.order_by('name')
#         ctx = {'links_menu': links_menu,}
#         return render(request, 'mainapp/category.html', ctx)


def main(request):
    current_url = resolve(request.path_info).url_name
    title = 'Главная'

    ctx = {'title': title,
           'current_year': current_year,
           'current_url': current_url,
           'products': products,
           }

    return render(request, 'mainapp/index.html', ctx)


def contact(request):
    title = 'Контакты'

    ctx = {'title': title,
           'current_year': current_year,
           }

    return render(request, 'mainapp/contact.html', ctx)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">

    <title>
    	{% block title %}{% endblock %}
    </title>

    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
	    <link rel="stylesheet" href="/static/fonts/font-awesome/css/font-awesome.css">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.4.0.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% endblock %}

</head>
<body>
	<div class="container">
        {% block menu %}

        {% endblock %}

        {% block content %}

        {% endblock %}

	</div>

    {% block footer %}
        <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {{ current_year }}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
    {% endblock %}

</body>
</html>

mainapp/templates/mainapp/category.html
{% extends 'mainapp/base.html' %}
{% load static %}

    {% block title %} {{ title|title }} {% endblock  %}

    {% block content %}
		<div class="slider">
			{% include 'mainapp/includes/header_clearfix.html' %}
		</div>

		<div class="details">
			<div class="links clearfix">
                {% include 'mainapp/includes/inc_categories_menu.html' %}
			</div>


			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{% static 'img/slider1.jpg' %}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>
				<div class="description">
					<h3 class="big-bold">{{ current_category.name }}</h3>
					<h3 class="red">{{ current_category.description }}</h3>

				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>

		<div class="clr"></div>
    {% endblock  %}

mainapp/templates/mainapp/includes/header_clearfix.html
<div class="header clearfix">
    <a href="/" class="logo"></a>
    <ul class="menu">

        <li><a href="{% url 'mainapp:index' %}"
               class="{% if request.path == '/' %}active{% endif %}">домой
            </a>
        </li>

        <li>
              <a href="{% url 'products:index' %}"
                 class="{% if request.resolver_match.namespace == 'products' %}
                          active
                        {% endif %}">
                продукты
              </a>
        </li>


        <li>
            <a href="{% url 'contact' %}"
                class="{% if request.path == '/contact/' %}active{% endif %}">контакты
            </a>
        </li>

        {% if user.is_authenticated %}
        <li>
           <div class="dropdown">
               <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                   {{ user.first_name|default:'Пользователь' }}
                   <span class="caret"></span>
               </a>
               <ul class="dropdown-menu">
                   <li>
                       <a href="{% url 'auth:edit' %}">
                           профиль
                       </a>
                   </li>
                   <li>
                       <a href="{% url 'ordersapp:orders_all' %}">
                           заказы
                       </a>
                   </li>
               </ul>
           </div>
        </li>

        {% endif %}
        {% if user.is_superuser %}
            <li>
              <a href="{% url 'admin:users' %}">админка</a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
              <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
              <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>

        <li>
            {% if basket %}
            <a href="{% url 'basket:view' %}"> в корзине: {{ basket|length }} товаров</a>
            {% else %}
            <a href="{% url 'basket:view' %}"> грустная пустая корзина</a>
            {% endif %}
        </li>

    </ul>

</div>

mainapp/templates/mainapp/includes/inc_categories_menu.html
    <ul class="links-menu">
      <li>
        <a href="{% url 'products:category' 0 %}"
           class="{% if request.resolver_match.kwargs.pk == '0' %}
                    active
                  {% endif %}">
          все
        </a>
      </li>
      {% for link in links_menu %}
        <li>
          <a href="{% url 'products:category' link.pk %}"
             class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                      active
                    {% endif %}">
            {{ link.name }}
          </a>
        </li>
      {% endfor %}
    </ul>

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}" 
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать 
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

    {% block title %} {{ title|title }} {% endblock  %}

    {% block content %}

      <div class="slider">

			{% include 'mainapp/includes/header_clearfix.html' %}

			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>

			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

      <div class="details">
            <div class="links clearfix">
              {% include 'mainapp/includes/inc_categories_menu.html' %}
            </div>

            <div class="products_list">
                    {% if category %}
                          <div class="title clearfix">
                            <h2>
                              Категория: "{{ category.name|title }}"
                            </h2>
                          </div>
                    {% endif %}

                      <div class="category-products clearfix">

                              {% for product in products %}
                                    <div class="block">
                                        <div class="text">
    {#                                      <img src="{% static 'img/icon-hover.png' %}" alt="hover">#}
                                          <h4>{{ product.name }}</h4>
                                          <p>{{ product.description }} </p>
                                        </div>
                                        <a href="{% url 'mainapp:product' product.pk %}">подробнее</a>
                                        <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                                    </div>
                              {% endfor %}
                      </div>

            </div>

            {% if hot_product %}
                <br><br>
                <h1>Hot products below</h1>
                <h3>{{ hot_product.name }}</h3>
                <h3>{{ hot_product.price }} <span>руб</span></h3>
                <h4>
{#                    <a href="{% url 'basket:add' %}"></a>#}
                    <a href="{% url 'mainapp:product' hot_product.pk %}">
                        подробнее
                    </a>

    {#                <a href="{% url 'basket:add' hot_product.pk %}"></a>#}
                </h4>
                <p>{{ hot_product.description }}</p>
            {% endif %}
      </div>

      <div class="clr"></div>

    {% endblock %}