authapp/urls.py
from django.urls import path, re_path

from authapp import views


app_name = 'authapp'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit/', views.edit, name='edit'),
    path('register/', views.register, name='register'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', views.verify, name='verify'),
]

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
	<div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>

            {% block content %}

            {% endblock %}
        </div>
	</div>
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}

    <form class="form-horizontal" action="{% url 'authapp:edit' %}" method="post"
          enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        {{ profile_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="сохранить">
    </form>

    <a href="{% url 'main' %}" class="btn btn-outline-info form-control"> на главную </a>

    <div class="user_avatar"><img src="/media/{{ user.avatar }}" alt=""></div>

{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <form class="form-horizontal" action="{% url 'authapp:login' %}" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>

    <br>


    <a href="{% url 'authapp:register' %}"
       class="btn btn-outline-success"> Зарегистрироваться </a>

    <a href="{% url 'social:begin' 'vk-oauth2' %}?next=/"
       class="btn btn-outline-info"> Вход через VK </a>



{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}

    <form class="form-horizontal" action="{% url 'authapp:register' %}" method="post"
          enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегаться">
    </form>

{#    <button class="btn btn-round form-control">#}
{#            <a href="{% url 'authapp:register' %}" class=""> зарегистрироваться </a>#}
{#    </button>#}

{% endblock %}

authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}

    {% if user %}
        <h3> Конгратуляции! </h3>
        <br>
        <h4> Пользователь {{ user.username }} подтвержден.</h4>
    {% else %}
        <h3> Верификация не пройдена. </h3>
    {% endif %}

    <br>
    <button class="btn btn-round form-control">
        <a href="{% url 'mainapp:index' %}" class=""> на главную</a>
    </button>

{% endblock %}