adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.users, name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('product/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

# we use name='users' in template: {% url 'adminapp:users' %}

adminapp/forms.py
from django import forms

from authapp.models import ShopUser
from authapp.forms import ShopUserChangeForm
from mainapp.models import ProductCategory, Product
from django.forms import ModelChoiceField



#
class ShopUserAdminEditForm(ShopUserChangeForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


#
class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

        # we need to show in form available categories from db
        self._category = forms.ModelChoiceField(queryset=ProductCategory.objects.all())
        self.fields['category'] = self._category

adminapp/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from authapp.models import ShopUser
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import user_passes_test
from mainapp.models import ProductCategory, Product


# R - read from CRUD
@user_passes_test(lambda u: u.is_superuser)
def users(request):
    title = 'админка/пользователи'

    users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser',
                                                 '-is_staff', 'username')

    ctx = {
        'title': title,
        'users_list': users_list,
    }

    return render(request, 'adminapp/users.html', ctx)


# C - create from CRUD
@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователи/создание'

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        user_form = ShopUserRegisterForm()

    ctx = {'title': title, 'update_form': user_form}

    return render(request, 'adminapp/user_update.html', ctx)


# U - update from CRUD
@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES,
                                          instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:user_update',
                                                args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)

    ctx = {'title': title, 'update_form': edit_form, }

    return render(request, 'adminapp/user_update.html', ctx)


# D - delete from CRUD
@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователи/удаление'

    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        # user.delete()
        # вместо удаления лучше сделаем неактивным
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin:users'))

    content = {'title': title, 'user_to_delete': user}

    return render(request, 'adminapp/user_delete.html', content)


# R - read from CRUD
@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'

    categoriest_list = ProductCategory.objects.all().order_by('-name')

    ctx = {
        'title': title,
        'categories_list': categoriest_list
    }

    return render(request, 'adminapp/categories.html', ctx)


# C - create from CRUD@user_passes_test(lambda u: u.is_superuser)
def category_create(request):
    title = 'категории/создание'

    if request.method == 'POST':
        prod_cat_form = ProductCategoryEditForm(request.POST)
        if prod_cat_form.is_valid():
            prod_cat_form.save()
            return HttpResponseRedirect(reverse('adminapp:categories'))
                                      # reverse('urlname')

    else:
        prod_cat_form = ProductCategoryEditForm()

    ctx = {'title': title, 'prod_cat_form': prod_cat_form}

    return render(request, 'adminapp/category_create.html', ctx)


# U - update from CRUD
@user_passes_test(lambda u: u.is_superuser)
def category_update(request, pk):
    title = 'категории/редактирование'

    edit_category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        edit_form = ProductCategoryEditForm(request.POST, instance=edit_category)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:category_update',
                                                args=[edit_category.pk]))

    else:
        edit_form = ProductCategoryEditForm()

    ctx = {'title': title, 'edit_form': edit_form}

    return render(request, 'adminapp/category_update.html', ctx)


# D - delete from CRUD
def category_delete(request, pk):
    title = 'категории/удаление'
    category_to_delete = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        category_to_delete.is_active = False
        category_to_delete.save()
        return HttpResponseRedirect(reverse('admin:categories'))

    ctx = {'title': title, 'category_to_delete': category_to_delete, }
    return render(request, 'adminapp/category_delete.html', ctx)


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):  # it's category pk!
    title = 'админка/продукт'

    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category__pk=pk).order_by('name')

    ctx = {
        'title': title,
        'category': category,
        'products_list': products_list,
    }

    return render(request, 'adminapp/products.html', ctx)


def product_create(request, pk): # it's category.pk
    title = 'товар/создать'
    _category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':

        product_form = ProductEditForm(request.POST)
        if product_form.is_valid():
            product_form.save()

            return HttpResponseRedirect(reverse('admin:products', args=[_category.pk]))
    else:
        product_form = ProductEditForm()

    ctx = {'title': title, 'product_form': product_form, 'category': _category}
    return render(request, 'adminapp/product_create.html', ctx)


def product_read(request, pk):
    pass


def product_update(request, pk):
    pass


def product_delete(request, pk):
    pass

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

    <title>
    	{% block title %}{% endblock %}
    </title>

    {% block css %}
        <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
        <link rel="stylesheet" type="text/css" href="/static/css/style.css">
	    <link rel="stylesheet" href="/static/fonts/font-awesome/css/font-awesome.css">
    {% endblock %}

    {% block js %}{% endblock %}

</head>

<body>
  <div class="admin_container">
    <div class="h2 text-center head">
      Админка
    </div>
    {% block menu %}
      <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
      </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="categories_list">
            <button class="new_category">
              <a href={% url 'admin:category_create' %}>
                новая категория
              </a>
            </button>

        {% for category in categories_list %}
              <div class="category_record
                    {% if category.is_active %}
                        active
                    {% endif %}">
                    <hr>
                    <br>
                    <div class="category_name">
                      category name: {{ category.name|title }}
                        <p>This category is:
                            <b>
                                {% if category.is_active %}
                                    Active
                                {% else %}
                                    Not Active
                                {% endif %}
                            </b>
                        </p>
                    </div>

                    <div class="category_desc">
                      category description: {{ category.description|title }}
                    </div>
                    <br>

                    <div class="category_actions">
                          <button>
                            <a href={% url 'admin:products' category.pk %}>
                              товары категории
                            </a>
                          </button>
                          <button>
                            <a href={% url 'admin:category_update' category.pk %}>
                              редактировать
                            </a>
                          </button>
                          <button>
                            <a href={% url 'admin:category_delete' category.pk %}>
                              удалить
                            </a>
                          </button>
                    </div>



              </div>
        {% endfor%}
    </div>

{% endblock %}

adminapp/templates/adminapp/category_create.html
{% block content %}

    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ prod_cat_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="создать категорию">
    </form>

    <button>
        <a href="{% url 'adminapp:categories' %}">back to categories list</a>
    </button>

{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="category_delete">
    Уверены, что хотите удалить {{ category_to_delete.name }} <br>


    <form action="{% url 'admin:category_delete' category_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:categories' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ edit_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/includes/inc_menu.html
<ul class="menu">
      <li><a href="{% url 'main' %}">
          на сайт
          </a>
      </li>
      <li><a href="{% url 'admin:users' %}" class="{% if request.resolver_match.url_name == 'users' %}
                    active
                  {% endif %}">
           пользователи
          </a>
      </li>
      <li><a href="{% url 'admin:categories' %}"
           class="{% if request.resolver_match.url_name == 'categories' or category.name %}
                    active
                  {% endif %}">
            категории
          {% if category %}
            :<span>{{ category.name }}</span>
          {% endif %}
        </a>
      </li>
{#      <li><a href="{% url 'admin:products' 1 %}" class="{% if request.resolver_match.url_name == 'products' %}">#}
{#                     active#}
{#                   {% endif %}#}
{#            товары#}
{#          </a>#}
{#      </li>#}
</ul>

adminapp/templates/adminapp/product_create.html
{% block content %}

    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ product_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="создать продукт">
    </form>

    <a href="{% url 'admin:products' category.pk %}">back</a>


{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <h1>category: {{ category }}</h1>
  <div class="products_list">
    <button class="new_product">
      <a href={% url 'admin:product_create' category.pk %}>
        новый продукт
      </a>
    </button>

    {% for product in products_list %}
      <div class="product_record">
        <img
          src="/media/{{product.image|default:'products_images/default.jpg'}}"
          alt="{{ product.name }}">
        <div class="product_name">
          {{ product.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href={% url 'admin:product_read' product.pk %}>
              подробнее
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_update' product.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_delete' product.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ product.price }} руб</p>
          <b>количество</b>
          <p>{{ product.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ product.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ user_to_delete.username }}
    {% if user_to_delete.first_name %}
      ({{ user_to_delete.first_name|title }}</b>
      {% if user_to_delete.last_name %}
        {{ user_to_delete.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin:user_delete' user_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:users' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="users_list">
    <button class="new_user">
      <a href={% url 'admin:user_create' %}>
        новый пользователь
      </a>
    </button>
    {% for user in users_list %}
      <div class="user_record {% if not user.is_active %}not_active{% endif %}">
        <img
          src="/media/{{ user.avatar|default:'users_avatars/default.jpg' }}"
          alt="{{ user.username }}">
        <div class="user_role">

              {% if user.is_superuser %}
                администратор
              {% else %}
                пользователь
              {% endif %}

              <button>
                <a href={% url 'admin:user_update' user.pk %}>
                  редактировать
                </a>
              </button>
              <button>
                <a href={% url 'admin:user_delete' user.pk %}>
                  удалить
                </a>
              </button>

        </div>
        <div class="user_name">
          <p><strong>{{ user.username }}</strong></p>
	    <p>
            {% if user.first_name %}
              <b>{{ user.first_name|title }}</b>
                {% if user.last_name %}
                  <p>{{ user.last_name|title }}</p>
                {% endif %}
            {% endif %}
          </p>
        </div>
        <div class="user_age">
          age:<br>
          {{ user.age }} лет
        </div>
        <div class="user_email">
          email:<br>
          {{ user.email }}
        </div>
        <div class="user_lastlogin">
          logged:<br>
          {{ user.last_login }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}