ordersapp/urls.py
from django.urls import path, re_path

from ordersapp import views


app_name = 'ordersapp'

urlpatterns = [
    re_path(r'^orders_all$', views.OrderList.as_view(), name='orders_all'),
    re_path(r'^order_create/$', views.OrderItemsCreate.as_view(), name='create_order'),
    re_path(r'^order_update/(?P<pk>\w+)/$', views.OrderItemsUpdate.as_view(), name='update_order'),
    re_path(r'^order_delete/(?P<pk>\w+)/$', views.OrderItemsDelete.as_view(), name='delete_order'),
    re_path(r'^order_detail/(?P<pk>\w+)/$', views.OrderRead.as_view(), name='read_order'),
    re_path(r'^order_forming_complete/(?P<pk>\w+)/$', views.order_forming_complete, name='order_forming_complete'),

]

ordersapp/models.py
from django.db import models

from django.conf import settings
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Текущий заказ: {self.pk}'

    def get_total_quantity(self):
        # items = self.orderitems.all()
        # return sum(list(map(lambda x: x.quantity, items)))
        # return sum([i.quantity for i in items])

        # items = self.orderitems.all().values_list('quantity', flat=True)
        items = self.orderitems.values_list('quantity', flat=True)
        return sum(items)

    def get_product_type_quantity(self):
        return self.orderitems.count()

    def get_total_cost(self):
        items = self.orderitems.select_related('product')
        # return sum(list(map(lambda x: x.quantity * x.product.price, items)))
        return sum([i.quantity * i.product.price for i in items])

    # переопределяем метод, удаляющий объект
    def delete(self):
        # for item in self.orderitems.all():
        #     item.product.quantity += item.quantity
        #     item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
           field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
   class Meta:
       model = OrderItem
       exclude = ()

   def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       for field_name, field in self.fields.items():
           field.widget.attrs['class'] = 'form-control'

ordersapp/views.py
from urllib import request

from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem


# def ordering_main(request):
#     pass

class OrderList(ListView):
   model = Order

   def get_queryset(self):
       return Order.objects.filter(user=self.request.user)


class OrderItemsCreate(CreateView):
   model = Order
   fields = []
   # form_class = OrderForm  # another way to pull fields
   success_url = reverse_lazy('ordersapp:orders_all')

   def get_context_data(self, **kwargs):
       data = super().get_context_data(**kwargs)
       OrderFormSet = inlineformset_factory(Order, OrderItem,
                                            form=OrderItemForm,
                                            extra=1)

       if self.request.POST:
           formset = OrderFormSet(self.request.POST, self.request.FILES)
       else:
           # basket_items = Basket.get_items(self.request.user) # original
           basket_items = self.request.user.basket.all()
           if len(basket_items):
               OrderFormSet = inlineformset_factory(Order, OrderItem,
                                                    form=OrderItemForm,
                                                    extra=len(basket_items))
               formset = OrderFormSet()
               for num, form in enumerate(formset.forms):
                   form.initial['product'] = basket_items[num].product
                   form.initial['quantity'] = basket_items[num].quantity
               # basket_items.delete() # это нужно делать в другом месте, позже, когда заказ создан
               # смотри метод form_valid ниже по коду.
           else:
               formset = OrderFormSet()

       data['orderitems'] = formset
       return data

   def form_valid(self, form):
       context = self.get_context_data()
       orderitems = context['orderitems']

       with transaction.atomic():
           form.instance.user = self.request.user
           self.object = form.save()
           if orderitems.is_valid():
               orderitems.instance = self.object
               orderitems.save()
           self.request.user.basket.all().delete()
       # # удаляем пустой заказ
       # if self.object.get_total_cost() == 0:
       #     self.object.delete()

       return super().form_valid(form)


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_all')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem,
                                            form=OrderItemForm,
                                            extra=1)
        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            data['orderitems'] = OrderFormSet(instance=self.object)

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

       # # удаляем пустой заказ
       # if self.object.get_total_cost() == 0:
       #     self.object.delete()

        return super().form_valid(form)


class OrderItemsDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:orders_all')


class OrderRead(DetailView):
   model = Order

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['title'] = 'заказ/просмотр'
       return context


def order_forming_complete(request, pk):
   order = get_object_or_404(Order, pk=pk)
   order.status = Order.SENT_TO_PROCEED
   order.save()

   return HttpResponseRedirect(reverse('ordersapp:orders_all'))

ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <title>
       {% block title %}
           {{ title|title }}
       {% endblock %}
   </title>

  {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
	    <link rel="stylesheet" href="/static/fonts/font-awesome/css/font-awesome.css">
  {% endblock %}

  {% block js %}
        <script src="{% static 'js/jquery-3.4.0.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="{% static 'js/orders_scripts.js' %}"></script>
  {% endblock %}

</head>
<body>
  <div class="container">
        {% block menu %}

        {% endblock %}

        {% block content %}

        {% endblock %}

	</div>
</body>
</html>

ordersapp/templates/ordersapp/includes/inc__order_actions.html
{% if object.status == 'FM' %}
    <a href="{% url 'orders:order_forming_complete' object.pk %}"
       class="btn btn-warning btn-round form-control last">
        соверишть покупку
    </a>
    <a href="{% url 'orders:delete_order' object.pk %}"
       class="btn btn-default btn-round form-control last">
        удалить
    </a>
{% endif %}

<a href="{% url 'orders:orders_all' %}"
   class="btn btn-info btn-round form-control last">
    к списку заказов
</a>
<a href="{% url 'mainapp:index' %}"
   class="btn btn-warning btn-round form-control last">
    на главную
</a>

ordersapp/templates/ordersapp/includes/inc__order_summary.html
{% if object %}
    <div class="h2">Заказ №{{ object.pk }} от {{ object.created|date:"Y-m-d H:i:s" }}</div>
    <hr>
    <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>
    <div class="h4">обновлен: {{ object.updated|date:"Y-m-d H:i:s" }}</div>
    <div class="h4">cтатус: {{ object.get_status_display }}</div>
    <hr>
    <div class="h4">
        общее количество товаров: <span class="order_total_quantity">{{ object.get_total_quantity }}</span>
    </div>
    <div class="h3">
        общая стоимость: <span class="order_total_cost">{{ object.get_total_cost }}</span> руб
    </div>
{% else %}
    <div class="h2">Новый заказ</div>
    <hr>
    <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>
    {% if basket.0 %}
        <div class="h4">
            общее количество товаров: <span class="order_total_quantity">{{ basket.0.total_quantity }}</span>
        </div>
        <div class="h3">
            общая стоимость: <span class="order_total_cost">{{ basket.0.total_cost }}</span> руб
        </div>
    {% endif %}
{% endif %}
<hr>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
    <div class="category_delete">
        <div class="h1">Уверены, что хотите удалить?</div>
        {% include 'ordersapp/includes/inc__order_summary.html' %}
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>

        <a href="{% url 'ordersapp:orders_all' %}" class="btn btn-success">отмена</a>
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}
{#% load my_tags %#}

{% block content %}
   {% include 'ordersapp/includes/inc__order_summary.html' %}
   <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">

               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc__order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}

{% block content %}
   {% include 'ordersapp/includes/inc__order_summary.html' %}
   <div class="order_form">
       <form method="post">
           {% csrf_token %}
        <!--  this field are empty for now    -->
           {{ form.as_p }}
           <table class="table">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr>
                           {% for field in form.visible_fields %}
                               <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                   {{ field.label|capfirst }}
                               </th>
                           {% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="formset_row">
                       {% for field in form.visible_fields %}
                           <td class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                               {% if forloop.first %}
                                   {% for hidden in form.hidden_fields %}
                                       {{ hidden }}
                                   {% endfor %}
                               {% endif %}
                               {{ field.errors.as_ul }}
                               {{ field }}
                           </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <input type="submit" value="сохранить" class="btn btn-secondary btn-round form-control last"></input>
           {% include 'ordersapp/includes/inc__order_actions.html' %}
       </form>
   </div>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}


{% block content %}
   <div class="h2 text-center head">
       Ваши заказы,
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
   </div>
   <table class="table orders_list">
       <thead>
         <tr>
           <th>ID</th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}
               {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'ordersapp:read_order' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:update_order' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:delete_order' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}
       </tbody>
   </table>

   <a href="{% url 'mainapp:index' %}" class="btn btn-info btn-round">
       на главную
   </a>

   <a href="{% url 'ordersapp:create_order' %}" class="btn btn-light btn-round">
       новый
   </a>

{% endblock %}